from enum import Enum



class ViolationEnum(Enum):
    RESOURCE_NOT_IN_IDLE_FREE_VIOLATION = 1
    SKILL_MISMATCH_VIOLATION = 2
    CONSTRAINT_NOT_FOUND_VIOLATION = 3
    SKIPPING_CONSTRAINT_CHECK_VIOLATION = 4
    CONSTRAINT_VIOLATION = 5

