[project]
name = "aastype3"
version = "0.1.0"
authors = [{name = "Ahmed Ibrahim Almohamed , email= ahmaedibrahim311@gmail.com"}]
description = "This is a project to build a Type 3 Asset Adminstartion Shell"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
